USE [Learning1]
GO

CREATE TABLE [dbo].[Powerplant](
	[ID] [int] IDENTITY(1,101) NOT NULL,
	[ID2] [int] NOT NULL,
	[Type] [varchar](30) NOT NULL,
	[SubType] [varchar](50) NULL,
 CONSTRAINT [PK_Powerplant] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, 
  ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
